-- MySQL Script generated by MySQL Workbench
-- Wed Apr 14 15:12:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bysj
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bysj
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bysj` DEFAULT CHARACTER SET utf8 ;
USE `bysj` ;

-- -----------------------------------------------------
-- Table `bysj`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bysj`.`users` ;

CREATE TABLE IF NOT EXISTS `bysj`.`users` (
  `user_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `password` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `phone` VARCHAR(11) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `salt` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username_UNIQUE` USING BTREE (`username`) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bysj`.`goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bysj`.`goods` ;

CREATE TABLE IF NOT EXISTS `bysj`.`goods` (
  `goods_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `goods_name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `created_at` DATETIME NOT NULL,
  `is_available` TINYINT NOT NULL DEFAULT 0,
  `cover` VARCHAR(512) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL COMMENT '封面',
  `cate_id1` BIGINT(20) NOT NULL COMMENT '一级目录',
  `cate_id2` BIGINT(20) NOT NULL COMMENT '二级目录',
  PRIMARY KEY (`goods_id`),
  INDEX `created_at` USING BTREE (`created_at`) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bysj`.`goods_property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bysj`.`goods_property` ;

CREATE TABLE IF NOT EXISTS `bysj`.`goods_property` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `goods_id` BIGINT(20) NOT NULL,
  `brand` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `price` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '价格，如10099，则为100.99元，后两位为小数',
  `description` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `used_time` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `fineness` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `can_bargain` TINYINT(1) NULL DEFAULT 0 COMMENT '是否可砍价，1可，0不可',
  `images` VARCHAR(1024) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `goods_id_UNIQUE` (`goods_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bysj`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bysj`.`categories` ;

CREATE TABLE IF NOT EXISTS `bysj`.`categories` (
  `cate_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) NOT NULL,
  `parent_id` BIGINT(20) NULL DEFAULT 0 COMMENT '父目录id，若为顶级则为0',
  PRIMARY KEY (`cate_id`),
  INDEX `parent_id` USING BTREE (`parent_id`) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bysj`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bysj`.`orders` ;

CREATE TABLE IF NOT EXISTS `bysj`.`orders` (
  `order_id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '订单id',
  `final_price` DOUBLE NOT NULL COMMENT '成交价',
  `payment_type` TINYINT(1) UNSIGNED NOT NULL COMMENT '支付类型，1在线支付，2货到付款',
  `created_at` DATETIME NOT NULL COMMENT '创建时间',
  `shipping_id` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL COMMENT '物流单号',
  `buyer_id` BIGINT(20) NOT NULL COMMENT '买家id',
  `seller_id` BIGINT(20) NOT NULL COMMENT '卖家id',
  `goods_id` BIGINT(20) NOT NULL COMMENT '商品id',
  `buyer_comment` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL COMMENT '买家留言',
  `rece_province` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT '收货省/地区',
  `rece_city` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT '收货城市',
  `rece_district` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT '收货区/县',
  `rece_address` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT '收货详细地址',
  `rece_phone` VARCHAR(11) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT '收货电话',
  `receiver` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL COMMENT '接收人',
  INDEX `buyer_id` (`buyer_id` ASC) INVISIBLE,
  INDEX `created_at` (`created_at` ASC) INVISIBLE,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bysj`.`goods_sku`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bysj`.`goods_sku` ;

CREATE TABLE IF NOT EXISTS `bysj`.`goods_sku` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `gid` INT UNSIGNED NOT NULL,
  `goods_skucol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `gid_UNIQUE` (`gid` ASC) VISIBLE,
  CONSTRAINT `goods_is`
    FOREIGN KEY (`gid`)
    REFERENCES `bysj`.`goods` (`goods_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bysj`.`orders_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bysj`.`orders_status` ;

CREATE TABLE IF NOT EXISTS `bysj`.`orders_status` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '唯一标识',
  `order_id` BIGINT(20) NOT NULL COMMENT '订单id',
  `status` INT(1) NOT NULL COMMENT '订单状态，1、未付款 2、已付款 3、已退款 4、交易成功 5、交易关闭',
  `created_at` DATETIME NOT NULL,
  `payment_at` DATETIME NULL DEFAULT NULL,
  `end_at` DATETIME NULL DEFAULT NULL,
  `close_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC) INVISIBLE,
  INDEX `status` USING BTREE (`status`) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bysj`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bysj`.`address` ;

CREATE TABLE IF NOT EXISTS `bysj`.`address` (
  `id` BIGINT(20) NOT NULL,
  `user_id` BIGINT(20) NOT NULL COMMENT '用户id',
  `rece_province` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `rece_city` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `rece_district` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `rece_address` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `receiver` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `rece_phone` VARCHAR(11) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `default` TINYINT(1) NULL DEFAULT 0 COMMENT '是否默认地址，1是，0否',
  PRIMARY KEY (`id`),
  INDEX `user_id` USING BTREE (`user_id`) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bysj`.`pay_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bysj`.`pay_log` ;

CREATE TABLE IF NOT EXISTS `bysj`.`pay_log` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `order_id` BIGINT(20) NOT NULL,
  `total_amount` BIGINT(20) NULL DEFAULT NULL COMMENT '支付总金额',
  `user_id` BIGINT(20) NULL DEFAULT NULL COMMENT '发起者id',
  `transaction_id` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL COMMENT '支付交易号码',
  `status` TINYINT(1) NULL DEFAULT NULL COMMENT '交易状态，1 未支付, 2已支付, 3 已退款, 4 支付错误, 5 已关闭',
  `created_at` DATETIME NULL DEFAULT NULL,
  `pay_at` DATETIME NULL DEFAULT NULL,
  `close_at` DATETIME NULL DEFAULT NULL,
  `refund_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` USING BTREE (`user_id`) INVISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
